title: Rebecka & Rasmus
description: Välkommen till vår bröllopssida!
theme: minima
url: "https://rebeckarasmus.github.io"
plugins:
  - jekyll-feed
  - jekyll-sitemap

header_pages:
  - index.md
  - boende.md
  - schema.md
  - osa.md
